baseurl = "https://bioinformatics.netlify.com/"
languageCode = "en-us"
title = "Introduction to Programming for beginners"
theme = "learn"

[params]
  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "Entomology and Plant Pathology Bioinformatics workshop"
  author = "Andres Espindola"
  showVisitedLinks = true
  themeVariant = "mine"
  disableLanguageSwitchingButton = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "Introduction to Programming for beginners"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/ngrafgr/epp_workshop"
weight = 10

[[Languages.en.menu.shortcuts]] 
name = "<i class='fa fa-fw fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/ngrafgr/epp_workshop"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-fw fa-bullhorn'></i> Credits"
url = "credits"
weight = 30